export const mockDishes = [
  {
    name: "Garlic Bread",
    shortDescription:
      "Crispy baguette slices topped with garlic butter and parsley.",
    price: "R45.00",
    dishCartegory: "Starter",
    dietaryCatergory: "Vegetarian",
    popularity: "High",
    arrivalDate: new Date("2025-08-01"),
    rating: 4,
  },
  {
    name: "Grilled Chicken Alfredo",
    shortDescription:
      "Creamy pasta with grilled chicken, parmesan, and fresh herbs.",
    price: "R120.00",
    dishCartegory: "Main",
    dietaryCatergory: "Halal",
    popularity: "High",
    arrivalDate: new Date("2025-07-20"),
    rating: 5,
  },
  {
    name: "Vegan Buddha Bowl",
    shortDescription: "Quinoa, roasted veggies, avocado, and tahini dressing.",
    price: "R95.00",
    dishCartegory: "Main",
    dietaryCatergory: "Vegan",
    popularity: "Medium",
    arrivalDate: new Date("2025-08-15"),
    rating: 4,
  },
  {
    name: "Chocolate Lava Cake",
    shortDescription: "Warm chocolate cake with a gooey molten center.",
    price: "R70.00",
    dishCartegory: "Dessert",
    dietaryCatergory: "Vegetarian",
    popularity: "High",
    arrivalDate: new Date("2025-08-10"),
    rating: 5,
  },
  {
    name: "Mango Smoothie",
    shortDescription: "Refreshing blend of ripe mango, yogurt, and honey.",
    price: "R55.00",
    dishCartegory: "Drink",
    dietaryCatergory: "Gluten-Free",
    popularity: "Low",
    arrivalDate: new Date("2025-07-28"),
    rating: 3,
  },
];
