import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

let signedIn = false;

const links = [
  {
    id: "0",
    href: "/",
    title: "Logo",
    type: "logo"
  },
  {
    id: "1",
    href: "/features",
    title: "Features",
    type: "content"
  },
  {
    id: "2",
    href: "/pricing",
    title: "Pricing",
    type: "content"
  },
  {
    id: "3",
    href: "/auth",
    title: signedIn ? "Sign-out" :"Sign-in",
    type: "button"
  },
  {
    id: "4",
    href: "/profile",
    title: "User Profile",
    type: "button"
  },
];

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>{children}</main>
      </body>
    </html>
  );
}
